sudo: required
services:
  - docker

before_install:
  - docker build -t jaypatel04/docker-react -f Dockerfile.dev .

script:
  - docker run -t jaypatel04/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2" # Region created in elastic beanstalk
  app: "docker" # App name given to AWS
  env: "Docker-env" # On AWS
  bucket_name: "elasticbeanstalk-us-west-2-<number>" # On AWS
  bucket_path: "docker" # On AWS
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrect_access_key:
    secure: "$AWS_SECRET_KEY"

